name: Build Database

concurrency: 
  group: database-build

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '15 2 * * *'    

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
  ASSET: geography.db.zip

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: setup requirements
        run: |-
          sudo apt-get install libsqlite3-mod-spatialite
          pip install -r requirements.txt
          npm install
      - name: build database
        run: make
      - name: prepare database for upload
        run: zip ${{ env.ASSET}} geography.db
      - name: release # if you have large artifacts upload to a repo's release.
        uses: WebFreak001/deploy-nightly@v1.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_ID: 83403879
        with:
          upload_url: https://uploads.github.com/repos/${{ github.repository }}/releases/${{ env.RELEASE_ID }}/assets{?name,label}
          release_id: ${{ env.RELEASE_ID }}
          asset_path: ${{ env.ASSET }}
          asset_name: ${{ env.ASSET }} # name to upload the release as, use $$ to insert date (YYYYMMDD) and 6 letter commit hash
          asset_content_type: application/zip # required by GitHub API
          max_releases: 7 # optional, if there are more releases than this matching the asset_name, the oldest ones are going to be deleted
  workflow-keepalive:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@v1        
